Document: react2fs
Title: Debian react2fs Manual
Author: <insert document author here>
Abstract: This manual describes what react2fs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/react2fs/react2fs.sgml.gz

Format: postscript
Files: /usr/share/doc/react2fs/react2fs.ps.gz

Format: text
Files: /usr/share/doc/react2fs/react2fs.text.gz

Format: HTML
Index: /usr/share/doc/react2fs/html/index.html
Files: /usr/share/doc/react2fs/html/*.html
